using System;
using System.Collections.Generic;

namespace DXApplication2
{
	public partial class Form1 : DevExpress.XtraEditors.XtraForm
	{
		List<Employees> employees;
		public Form1()
		{
			InitializeComponent();
			employees = Repostory.Load();

			// This line of code is generated by Data Source Configuration Wizard
			tB_ItemTableAdapter1.Fill(billsDataSet1.TB_Item);
		}

		private void Form1_Load(object sender, EventArgs e)
		{
			// TODO: This line of code loads data into the 'billsDataSet.TB_Item' table. You can move, or remove it, as needed.
			this.tB_ItemTableAdapter.Fill(this.billsDataSet.TB_Item);


		}
	}
}
